### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by myadla**
Added the description for tests under README file

Depends-On: https://github.com/infrawatch/feature-verification-tests/pull/104
Depends-On: https://github.com/infrawatch/feature-verification-tests/pull/131

### CODE REVIEW

**Comment by elfiesmelfie** [comment]
> Unable to freeze job graph: Job functional-tests-on-osp18 depends on openstack-k8s-operators-content-provider which was not run.

This is not related to this change; there is job missing from zuul

**Comment by elfiesmelfie** [comment]
recheck

**Comment by elfiesmelfie** [comment]
I added a debug flag to the github-check pipeline to get some more information about how zuul is resolving the job dependency graph.

It initially looks like the build is just working, since the content provider and functional test job are both queued

**Comment by elfiesmelfie** [comment]
> Unable to freeze job graph: Job functional-tests-on-osp18 depends on openstack-k8s-operators-content-provider which was not run.

This makes absolutely no sense. The job appears to have run and passed when I had `debug: true` set for the pipeline.

**Comment by elfiesmelfie** [comment]
> openstack-k8s-operators-content-provider

I checked the definition of the content provider job.
The list of irrelevant files includes `*/*.md`
Since this PR only changed the `roles/telemetry_autoscaling/README.md`, the content provider didn't run.

When I added `debug: true` to the github-check pipeline in .zuul.yaml, the content provider job started running because there was a change to a file that was not irrelevant.

I will update the base jobs so that the irrelevant files list matches the content provider job.

**Comment by elfiesmelfie** [comment]
recheck

**Comment by elfiesmelfie** [comment]
recheck

**Comment by elfiesmelfie** [comment]
recheck

**Comment by myadla** [comment]
Could you provide review for this ?

**Review by elfiesmelfie — APPROVED** [review]

**Comment by elfiesmelfie** [comment]
recheck

**Comment by elfiesmelfie** [comment]
I think we need to add a no-op zuul job to this, in order for Zuul to run when only irrelevant-files are changed.

I will work on adding that in now.

**Comment by elfiesmelfie** [comment]
recheck

**Comment by elfiesmelfie** [comment]
recheck

**Review by elfiesmelfie — APPROVED** [review]

**Review by lnatapov — APPROVED** [review]
lgtm

**Pull request merged**
