### PR TITLE
Add zuul report

### PR DESCRIPTION
**Pull request by mgirgisf**
This PR gurante that the zuul job will fail in case of any failure happened in the tasks with the test cases IDs
https://github.com/infrawatch/feature-verification-tests/pull/91

And it generate 2 log files that is being uploaded to the zuul logs.:
1- summary_results.log  that contains a summary report : ci-framework-data/logs/functional-tests/summary_results.log
2-test_run_result.log that has the old format for each task and its state.  ci-framework-data/logs/functional-tests/test_run_result.log

### CODE REVIEW

**Comment by elfiesmelfie** [comment]
Please sync this with the latest version of the master branch. https://github.com/infrawatch/feature-verification-tests/pull/91 has merged, so syncing will get the up[dates that added all the test case IDs, and we can see a more representative output from the updates.

**Review by elfiesmelfie — CHANGES_REQUESTED** [review]
Please sync this with the current master branch to get changes added in https://github.com/infrawatch/feature-verification-tests/pull/91

**Comment by mgirgisf** [comment]
recheck

**Review by elfiesmelfie — APPROVED** [review]

**Comment by elfiesmelfie** [comment]
Looks good to me.
For others reviewing, the output files are available here: https://logserver.rdoproject.org/93/93/c3e1e8d96e96a13d10e637c6afd00b66a0d61f54/github-check/functional-tests-on-osp18/a593b4b/controller/ci-framework-data/logs/functional-tests/

**Review by ayefimov-1 — APPROVED** [review]
Looks okay to me.

**Pull request merged**
