### PR TITLE
[zuu] Add osp18 job

### PR DESCRIPTION
**Pull request by mgirgisf**

### CODE REVIEW

**Comment by elfiesmelfie** [comment]
check-rdo

**Comment by mgirgisf** [comment]
its already merged https://review.rdoproject.org/r/plugins/gitiles/config/+/refs/heads/master/zuul/rdo.yaml#1270

and I can found it here also https://review.rdoproject.org/zuul/project/github.com/infrawatch/feature-verification-tests I think I'm missing something else

**Comment by elfiesmelfie** [comment]
recheck

**Comment by elfiesmelfie** [comment]
recheck

**Pull request closed without merging**
