### PR TITLE
[telemetry_autoscaling] Add test prefix to tests

### PR DESCRIPTION
**Pull request by elfiesmelfie**
This allows the custom_junit plugin to record the tests.
Depends-On: https://github.com/infrawatch/feature-verification-tests/pull/132

### CODE REVIEW

**Comment by mgirgisf** [comment]
recheck

**Comment by mgirgisf** [comment]
recheck

**Comment by mgirgisf** [comment]
recheck

**Comment by elfiesmelfie** [comment]
Duplicate of https://github.com/infrawatch/feature-verification-tests/pull/143

**Pull request closed without merging**
